### ISSUE TITLE
error: ‘make_unique’ is not a member of ‘geos::detail’

### ISSUE THREAD

**Issue by eyal0** [libgeos/geos#940]
I continue to see the same issue as in https://github.com/libgeos/geos/issues/922

Which is might be a duplicate of https://github.com/libgeos/geos/issues/860

I'm compiling on latest main branch.

```
└──> git bisect bad
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
15a03919d16ae78387e87e26f9a9f3da7af21543
08ea625842a0708e764c6e01a4538fd55e0663d0
213f1986c6a8ffcc93b0b8c403b3df24548d090f
96160b1b18d171bca09d56803fa4e49532582658
We cannot bisect more!
```

One of those commits is the problem.  There was a secondary problem that occurred as the same time, too.

One of them is the `make_unique` problem:

```
/home/esoha/private/geos/include/geos/index/strtree/TemplateSTRtreeDistance.h:99:39: error: ‘make_unique’ is not a member of ‘geos::detail’
   99 |                     minPair = detail::make_unique<NodePair>(pair);
```

The other is something else:

```
In file included from /home/esoha/private/geos/tests/unit/geom/CoordinateSequenceTest.cpp:8:
/home/esoha/private/geos/include/geos/geom/CoordinateSequence.h: In instantiation of ‘void geos::geom::CoordinateSequence::forEach(F&&) const [with F = tut::test_object<Data>::test<53>::<lambda(int&)>&]’:
/home/esoha/private/geos/tests/unit/geom/CoordinateSequenceTest.cpp:1410:29:   required from here
/home/esoha/private/geos/include/geos/geom/CoordinateSequence.h:635:92: error: no match for call to ‘(tut::test_object<Data>::test<53>::<lambda(int&)>) (const geos::geom::CoordinateXY&)’
  635 |             case CoordinateType::XY:    for (const auto& c : items<CoordinateXY>())   { fun(c); } break;
      |                                                                                         ~~~^~~
```

**Comment by eyal0** [comment]
The problem is that my build is somehow choosing to use c++11 and make_unique is only available in c++14.

Looks like my cmake files got screwed up when I mixed the `./configure` with `cmake` in a directory.

Running `git clean -i -x -d` and then `mkdir build; cd build; cmake ..; make -j 20` fixed the problem.
